### ISSUE TITLE
Slight improvement suggestions

### ISSUE THREAD

**Issue by JosefWN** [systemli/prometheus-jitsi-meet-exporter#73]
- Perhaps the templating in `main.go` is intentional to keep dependencies to a minimum? If not the official Prometheus client for Go is pretty easy to use to achieve the same effect: https://github.com/prometheus/client_golang
- The go version could be bumped in `go.mod` from 1.14 to 1.17
- `/health`(or `/healthz`) is deprecated in Kubernetes in favor of `/livez` as of v1.16: https://kubernetes.io/docs/reference/using-api/health-checks/#api-endpoints-for-health

Can create a PR later if any of the suggestions are of interest.

**Comment by 0x46616c6b** [comment]
Hey, thanks for your review and your suggestions. I already updated the version in `go.mod` (see #80). 

The templating in `main.go` is intentional as you guessed. At the moment I don't see a benefit of using the official Client from Prometheus. So we only have Counter and Gauges here and nothing like Histogram where the client can really help.

If you want to adjust the Endpoint for Healthchecks I don't have hard feelings for this. So feel free to open an PR.
